# https://github.com/realm/SwiftLint#configuration
# https://realm.github.io/SwiftLint/rule-directory.html

included: source
disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - private_over_fileprivate
  - redundant_discardable_let
  - type_body_length

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: false

vertical_whitespace:
  max_empty_lines: 2

switch_case_alignment:
  indented_cases: true
