# https://github.com/realm/SwiftLint#configuration
# https://realm.github.io/SwiftLint/rule-directory.html
# swiftlint rules

included: source

analyzer_rules:
  - explicit_self

opt_in_rules:
  - explicit_acl
  - explicit_top_level_acl
  - modifier_order
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - nesting
  - opening_brace
  - private_over_fileprivate
  - reduce_boolean
  - todo
  - type_body_length
  - unneeded_override

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: false

vertical_whitespace:
  max_empty_lines: 2

switch_case_alignment:
  indented_cases: true
