# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# https://github.com/peripheryapp/periphery/blob/master/.github/workflows/test.yml

name: Lint & Test

on:
  push: { branches: [ main ] }
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  skip:
    name: Pre-Check & Skip
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
    steps:
      - name: Skip duplicate actions
        id: check
        uses: fkirc/skip-duplicate-actions@v5

  main:
    name: Lint & Test
    needs: skip
    if: needs.skip.outputs.should_skip != 'true'
    runs-on: macos-latest

    steps:

      # 🚦 Prepare & Checkout

      - name: Checkout Git
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up Homebrew
        run: brew install mint xcbeautify

      - name: Cache Mint
        id: cache-mint
        uses: actions/cache@v5
        with:
          path: ~/.mint
          key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-

      - name: Set up Mint
        run: mint bootstrap


      # 💅 Lint

      - name: Run SwiftLint
        run: mint run swiftlint lint --quiet --strict ./source

      - name: Run SwiftFormat
        run: mint run swiftformat --lint ./source


      # 🐧 SPM

      - name: Cache SPM
        id: cache-spm
        uses: actions/cache@v5
        with:
          path: |
            dependency/Swift
            dependency/Xcode
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.swift', 'Package.resolved', 'Observatory.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Resolve Swift dependencies
        if: steps.cache-spm.outputs.cache-hit != 'true'
        run: swift package --scratch-path dependency/Swift resolve


      # 🛠️ Xcode

      - name: Resolve Xcode dependencies
        if: steps.cache-spm.outputs.cache-hit != 'true'
        run: |
          xcodebuild \
            -workspace "Observatory.xcworkspace" \
            -scheme "Observatory" \
            -resolvePackageDependencies \
            -clonedSourcePackagesDirPath dependency/Xcode


      # 🚧 Build

      - name: Build Swift tests
        run: swift build --build-tests --scratch-path dependency/Swift

      - name: Build Xcode tests
        run: |
          set -o pipefail && xcodebuild clean build-for-testing \
            -workspace "Observatory.xcworkspace" \
            -scheme "Observatory-Test" \
            -destination "platform=macOS,arch=$(uname -m)" \
            -disableAutomaticPackageResolution \
            -clonedSourcePackagesDirPath "dependency/Xcode" \
            | tee "build.log" | xcbeautify


      # 🧪 Test

      - name: Test Swift
        run: set -o pipefail && swift test --scratch-path dependency/Swift 2>&1 | xcbeautify

      - name: Test Xcode
        env:
          TEST_RUNNER_ACCESSIBILITY_CONTROL: 0
        run: |
          set -o pipefail && xcodebuild test \
            -workspace "Observatory.xcworkspace" \
            -scheme "Observatory-Test" \
            -destination "platform=macOS,arch=$(uname -m)" \
            -disableAutomaticPackageResolution \
            -clonedSourcePackagesDirPath "dependency/Xcode" \
            | xcbeautify
